### ISSUE TITLE
Maybe not the image you're hoping for?

### ISSUE THREAD

**Issue by jposi** [GSA/technology-modernization-fund#8]
The golden eagle icon is eerily similar to some other iconography that I think you don't want to invoke here. Happy to chat, and I bet so would @mogul.

https://twitter.com/bmogilefsky/status/1006725058151186434

**Comment by jposi** [comment]
The offending image, AFAICT is labeled gold-eagle.

**Comment by mogul** [comment]
https://twitter.com/tbaxter/status/1006726759155490816?s=19

**Comment by mogul** [comment]
I'm removing my tweet as the observation is more productive to deliver here, but for posterity...
![image](https://user-images.githubusercontent.com/47762/41329911-44a5232e-6e85-11e8-8208-d5dbdc61e0a5.png)

**Comment by lanebecker** [comment]
Hope you're happier with the new one!

**Comment by mogul** [comment]
I was out on vacation and missed the resolution here... OMG I love it!! That's a huge improvement. Thank you for addressing this! 🇺🇸
